apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: chaos-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: chaos-sa
  namespace: default
roleRef:
  kind: Role
  name: chaos-role
  apiGroup: rbac.authorization.k8s.io

