global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager-service:9093'

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['flask-service.default.svc.cluster.local:5000']

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: flask-app|chaos-app

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

