# alertmanager-config.yaml
global:
  resolve_timeout: 5m

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#new-channel'
        send_resolved: true
        title: '{{ .Status | toUpper }}: {{ .CommonAnnotations.summary }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}  
            *Description:* {{ .Annotations.description }}  
            *Severity:* {{ .Labels.severity }}
          {{ end }}

