apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - 'alertmanager-service:9093'

    rule_files:
      - /etc/prometheus-rules/alert-rules.yaml

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'flask-app'
        static_configs:
          - targets: ['flask-service:80']

      - job_name: 'chaos-app'
        static_configs:
          - targets: ['chaos-app-service:8080']

